# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tblondelle@home
email: thomas.blondelle@gmail.com
description: >
  Personal website to store some projects that I needed and that I have done. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tblondelle.github.io"
github_username:  tblondelle

# Build settings
markdown: kramdown
